[package]
edition = "2021"
name = "native-utils"
version = "0.0.0"

[workspace]
members = ["migration"]

[features]
default = []
noarray = []
napi = ["dep:napi", "dep:napi-derive"]

[lib]
crate-type = ["cdylib", "lib"]

[dependencies]
async-trait = "0.1.68"
cfg-if = "1.0.0"
chrono = "0.4.24"
cuid2 = "0.1.0"
derive_more = "0.99.17"
jsonschema = "0.17.0"
once_cell = "1.17.1"
parse-display = "0.8.0"
rand = "0.8.5"
schemars = { version = "0.8.12", features = ["chrono"] }
sea-orm = { version = "0.11.3", features = ["sqlx-postgres", "postgres-array", "sqlx-sqlite", "runtime-tokio-rustls"] }
serde = { version = "1.0.163", features = ["derive"] }
serde_json = "1.0.96"
thiserror = "1.0.40"
tokio = { version = "1.28.1", features = ["full"] }
utoipa = "3.3.0"

# Default enable napi4 feature, see https://nodejs.org/api/n-api.html#node-api-version-matrix
napi = { version = "2.13.1", default-features = false, features = ["napi6", "tokio_rt"], optional = true }
napi-derive = { version = "2.12.0", optional = true }
basen = "0.1.0"

[dev-dependencies]
pretty_assertions = "1.3.0"

[build-dependencies]
napi-build = "2.0.1"

[profile.release]
lto = true
