pipeline:
  publish-docker-tag:
    image: plugins/kaniko
    settings:
      repo: thatonecalculator/firefish
      # Uses the tag from git for the container tag
      tags: ${CI_COMMIT_TAG}
      dockerfile: Dockerfile
      username:
        # Secret 'docker_username' needs to be set in the CI settings
        from_secret: docker_username
      password:
        # Secret 'docker_password' needs to be set in the CI settings
        from_secret: docker_password
    when:
      # Push new version when version tag is created
      event: tag
      tag: v*
