name: Lint

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/**'
      - 'custom/**'
  pull_request:
    paths:
      - 'packages/**'
      - 'custom/**'

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true

    strategy:
      matrix:
        node-version: [20.x]

    steps:
    - uses: actions/checkout@v3.3.0
      with:
        fetch-depth: 0
        submodules: true
    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 8
        run_install: false
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3.6.0
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - run: corepack enable
    - run: pnpm i --frozen-lockfile
    - name: Lint Code
      run: pnpm lint