name: Publish image (develop)

on:
  push:
    branches:
      - develop
    paths:
      - 'packages/**'
      - 'custom/**'
      - 'package.json'
  workflow_dispatch:

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: transfem-org/transfish

jobs:
  push_to_registry:
    name: Push Docker image to GHCR
    runs-on: ubuntu-latest
    if: github.repository == 'transfem-org/TransFish'
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3.3.0
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.3.0
        with:
          platforms: linux/amd64
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and Push to GHCR
        id: build
        uses: docker/build-push-action@v4
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          push: true
          platforms: ${{ steps.buildx.outputs.platforms }}
          provenance: false
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:develop
          labels: develop
          cache-from: type=gha
          cache-to: type=gha,mode=max
      - name: Pull update for transfem.social server
        if: steps.build.outcome == 'success'
        uses: indiesdev/curl@v1.1
        with:
          url: ${{ secrets.PUSH_UPDATE_PULL }}
          method: POST
          timeout: 600000
